# Site settings
title: Magic&#58; The Gathering API
email: support@mtgapi.com
description: > # this means to ignore newlines until "baseurl:"
An easy to use API for Magic: The Gathering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mtgapi.com" # the base hostname & protocol for your site
twitter_username:  kernelcurry
github_username:   michaelcurry
linkedin_username: michaeliancurry

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# plugins
gems: ['jekyll-less', 'jekyll-sitemap', 'jekyll-redirect-from', 'jekyll-press']

# jekyll press to compress all of the things
jekyll-press:
  exclude: 'sitemap.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options